### ISSUE TITLE
Error in App.tsx

### ISSUE THREAD

**Issue by abhishekalbert** [insidesherpa/bank-mergeCoTechTask2#289]
Hi does anyone know why it's showing error even when I did things as said in the guideline 

`/**
   * Get new data from server and update the state with the new data
   */
  getDataFromServer() {
    let x = 0;
    const interval = setInterval(() => {
      DataStreamer.getData((serverResponds: ServerRespond[]) => {
        this.setState {
          data: serverResponds,
          showGraph; true,
        });
      });
      x++;
      if (x > 1000) {
        clearInterval(interval);
      }
    },100);
  }`

[Screen Shot 2020-08-24 at 11 00 38 AM](https://user-images.githubusercontent.com/31933565/91007244-162eba80-e5f9-11ea-9ae8-403fabb7b162.png)

**Comment by kaursimranjeet** [comment]
There is an opening parenthesis after setState in this line --  this.setState({
It was not visible in the 'making_changes' file because of the red block.
