### ISSUE TITLE
× NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8080/query?id=1'

### ISSUE THREAD

**Issue by Yeison2020** [insidesherpa/bank-mergeCoTechTask2#346]
I hope you're having a great day, guys. 
My problem is (
NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'http://localhost:8080/query?id=1).

I tried turning off the firewall and changing the ports from 8080 to 8085 and vice versa. Additionally, I reinstalled the react body dependencies and check every line in the server.py file. I would appreciate any recommendations.
Thank you very much.

**Comment by souromisen** [comment]
Hi! I am facing the same problem in Task 3. Did you end up finding a solution to this issue?
If so, please do let me know!

**Comment by Ritu-Dhull** [comment]
heyy,did you find solution to the issue?I'm facing same in task 3
