### ISSUE TITLE
npm install/start

### ISSUE THREAD

**Issue by AhmadAsha01** [insidesherpa/bank-mergeCoTechTask2#350]
Hey guys , I need help with this one, I don't really know what's wrong, any suggestions are welcomed... and thanks in advance
![22](https://user-images.githubusercontent.com/96956596/147859060-10ce08e0-8682-48fb-b8cf-65009957aacc.PNG)

**Comment by abhishek2021005** [comment]
Hey @AhmadAsha01 i am also facing same issue, can u please explain how u got rid of this?
